# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [5]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# # Import API key
# from api_keys import g_key

# Google API Key
from api_keys import g_key
from api_keys import weather_api_key
from itertools import product
from itertools import permutations

# Access maps with unique API key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [6]:
pd.read_csv('output_data\cities.csv', delimiter = ',')

,city,country,lat,lng,temp,humidity,cloudiness,wind speed
0,Lompoc,US,34.64,34.64,54.81,66,1,3.36
1,Saint-Philippe,RE,-21.36,-21.36,72.30,73,42,3.36
2,Hobart,AU,-42.88,-42.88,41.34,93,75,6.93
3,East London,ZA,-33.02,-33.02,64.40,55,0,25.28
4,Cuamba,MZ,-14.80,-14.80,83.37,48,58,7.76
...,...,...,...,...,...,...,...,...
586,Sungai Penuh,ID,-2.08,-2.08,66.90,95,100,0.85
587,Aksarka,RU,66.56,66.56,41.65,88,100,12.21
588,Baharly,TM,38.44,38.44,63.68,24,0,8.03
589,Xingcheng,CN,40.62,40.62,46.15,46,65,10.83
590,Manicoré,BR,-5.81,-5.81,98.91,36,26,3.09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure